language: python

env:
  - PYTHON_VERSION=2.7
  - PYTHON_VERSION=3.6

before_install:
  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda
install:
    - conda env create --file environment.yml python=${PYTHON_VERSION}
    - source activate celer-env
    - conda install --yes --quiet nose coverage
    - pip install flake8 check-manifest
    - pip install codecov
    - python setup.py install
script:
    - make
    - make test-coverage
    - flake8 --count celer
after_success:
- codecov
