coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 0.01
    patch: false
    changes: false
  ignore:
    - "examples/download_preprocess_finance.py"
comment:
  layout: "header, diff, sunburst, uncovered"
behavior: default
