name: linter

on: push

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Lint with flake
        run: |
          pip install --upgrade pip
          pip install flake8
          flake8 --max-line-length=88 celer/
          flake8 --max-line-length=88 examples/